#mesh: touchplate.apg
diffuse_map: firesprite_green.png
specular_map: total_transp.png
normal_map: blankNM.png
casts_shadow: 0
type: generic
uses_sprite: 1
sprite_map_rows 4
sprite_map_cols 4
sprite_y_offset 1.0
radius: 0.0
height: 0.0

lamp_offset_pos (0.0, 1.5, 0.0)
lamp_diffuse_colour (0.2, 1.0, 0.2)
lamp_specular_colour (0.2, 0.7, 0.2)
lamp_range 6

#particles: brazier_smoke.particles
#particles_offset: (0.0, 2.0, 0.0)

scale: (0.7, 0.7, 0.7)
