mesh: diamond.apg
outlines_mesh: diamond_smooth.apg
diffuse_map: diamond_diff.png
specular_map: diamond_spec.png
normal_map: blankNM.png
casts_shadow: 0

character_activated: 1
npc_activated: 0
hide_after_triggering: 1
trigger_only_once: 1

type: diamond_trigger
uses_sprite: 0
scale: (1.0, 1.0, 1.0)

particles: magical.particles
particles_offset: (0.0, 1.6, 0.0)

sound_activate: MAGIC_SPELL_Quick_Deep_Fast_Attack_Echo_Fade_stereo.wav
