#mesh: corner_webs_smooth.apg
#outlines_mesh: corner_webs_smooth.apg
diffuse_map: slime_pool_dm.png
specular_map: slime_pool_sm.png
normal_map: blankNM.png
casts_shadow: 0 # all transparent props are ignored for shadows anyway
transparent: 1
draw_outlines: 0
uses_sprite: 1
sprite_map_rows 1
sprite_map_cols 1
sprite_y_offset 0.0
sprite_timer 0.75

type: generic
#type: no_physics

particles: slime_drip.particles
particles_offset: (0.0, 10.0, 0.0)

scale: (0.4, 0.4, 0.4)
