mesh: wall_torch_2.apg
#i smoothed the mesh so don't need this any more:
#outlines_mesh: wall_torch_smooth.apg
diffuse_map: wall_torch_2_dm.png
specular_map: blankSM.png
normal_map: blankNM.png
casts_shadow: 1

type: prop

lamp_offset_pos (-0.69, 2.0, 0.0)
lamp_diffuse_colour (0.2, 0.2, 1.0)
lamp_specular_colour (0.7, 0.7, 0.8)
lamp_range 6

particles: torch_blue.particles
particles_offset: (0.0, 1.6, -0.69)
