
package Fmod is

    type Fmod_Result is (Fmod_Ok,
                         Fmod_Err_Badcommand,
                         Fmod_Err_Channel_Alloc,
                         Fmod_Err_Channel_Stolen,
                         Fmod_Err_Dma,
                         Fmod_Err_Dsp_Connection,
                         Fmod_Err_Dsp_Dontprocess,
                         Fmod_Err_Dsp_Format,
                         Fmod_Err_Dsp_Inuse,
                         Fmod_Err_Dsp_Notfound,
                         Fmod_Err_Dsp_Reserved,
                         Fmod_Err_Dsp_Silence,
                         Fmod_Err_Dsp_Type,
                         Fmod_Err_File_Bad,
                         Fmod_Err_File_Couldnotseek,
                         Fmod_Err_File_Diskejected,
                         Fmod_Err_File_Eof,
                         Fmod_Err_File_Endofdata,
                         Fmod_Err_File_Notfound,
                         Fmod_Err_Format,
                         Fmod_Err_Header_Mismatch,
                         Fmod_Err_Http,
                         Fmod_Err_Http_Access,
                         Fmod_Err_Http_Proxy_Auth,
                         Fmod_Err_Http_Server_Error,
                         Fmod_Err_Http_Timeout,
                         Fmod_Err_Initialization,
                         Fmod_Err_Initialized,
                         Fmod_Err_Internal,
                         Fmod_Err_Invalid_Float,
                         Fmod_Err_Invalid_Handle,
                         Fmod_Err_Invalid_Param,
                         Fmod_Err_Invalid_Position,
                         Fmod_Err_Invalid_Speaker,
                         Fmod_Err_Invalid_Syncpoint,
                         Fmod_Err_Invalid_Thread,
                         Fmod_Err_Invalid_Vector,
                         Fmod_Err_Maxaudible,
                         Fmod_Err_Memory,
                         Fmod_Err_Memory_Cantpoint,
                         Fmod_Err_Needs3D,
                         Fmod_Err_Needshardware,
                         Fmod_Err_Net_Connect,
                         Fmod_Err_Net_Socket_Error,
                         Fmod_Err_Net_Url,
                         Fmod_Err_Net_Would_Block,
                         Fmod_Err_Notready,
                         Fmod_Err_Output_Allocated,
                         Fmod_Err_Output_Createbuffer,
                         Fmod_Err_Output_Drivercall,
                         Fmod_Err_Output_Format,
                         Fmod_Err_Output_Init,
                         Fmod_Err_Output_Nodrivers,
                         Fmod_Err_Plugin,
                         Fmod_Err_Plugin_Missing,
                         Fmod_Err_Plugin_Resource,
                         Fmod_Err_Plugin_Version,
                         Fmod_Err_Record,
                         Fmod_Err_Reverb_Channelgroup,
                         Fmod_Err_Reverb_Instance,
                         Fmod_Err_Subsounds,
                         Fmod_Err_Subsound_Allocated,
                         Fmod_Err_Subsound_Cantmove,
                         Fmod_Err_Tagnotfound,
                         Fmod_Err_Toomanychannels,
                         Fmod_Err_Truncated,
                         Fmod_Err_Unimplemented,
                         Fmod_Err_Uninitialized,
                         Fmod_Err_Unsupported,
                         Fmod_Err_Version,
                         Fmod_Err_Event_Already_Loaded,
                         Fmod_Err_Event_Liveupdate_Busy,
                         Fmod_Err_Event_Liveupdate_Mismatch,
                         Fmod_Err_Event_Liveupdate_Timeout,
                         Fmod_Err_Event_Notfound,
                         Fmod_Err_Studio_Uninitialized,
                         Fmod_Err_Studio_Not_Loaded,
                         Fmod_Err_Invalid_String,
                         Fmod_Err_Already_Locked,
                         Fmod_Err_Not_Locked,
                         Fmod_Err_Record_Disconnected,
                         Fmod_Err_Toomanysamples,

                         Fmod_Result_Forceint  --  = 65536A
                        );
    pragma Convention (C, Fmod_Result);

    --  for Fmod_Result use (16#65536A#);

end Fmod;
