
package Assimp_Config is

   AI_CONFIG_IMPORT_GLOBAL_KEYFRAME : String := "IMPORT_GLOBAL_KEYFRAME";
   AI_CONFIG_IMPORT_MD3_KEYFRAME    : String := "IMPORT_MD3_KEYFRAME";
   AI_CONFIG_IMPORT_MD2_KEYFRAME    : String := "IMPORT_MD2_KEYFRAME";
   AI_CONFIG_IMPORT_MDL_KEYFRAME    : String := "IMPORT_MDL_KEYFRAME";
   AI_CONFIG_IMPORT_MDC_KEYFRAME    : String := "IMPORT_MDC_KEYFRAME";
   AI_CONFIG_IMPORT_SMD_KEYFRAME    : String := "IMPORT_SMD_KEYFRAME";
   AI_CONFIG_IMPORT_UNREAL_KEYFRAME : String := "IMPORT_UNREAL_KEYFRAME";

   AI_CONFIG_IMPORT_AC_SEPARATE_BFCUL : String := "IMPORT_AC_SEPARATE_BFCULL";

end Assimp_Config;
