
package Post_Process is

   type AI_Post_Process_Steps is (AI_Process_Calc_Tangent_Space,
                                  AI_Process_Join_Identical_Vertices,
                                  AI_Process_Make_Left_Handed,
                                  AI_Process_Triangulate,
                                  AI_Process_Remove_Component,
                                  AI_Process_Gen_Normals,
                                  AI_Process_Gen_Smooth_Normals,
                                  AI_Process_Split_Large_Meshes,
                                  AI_Process_Pre_Transform_Vertices,
                                  AI_Process_Limit_Bone_Weights,
                                  AI_Process_Validate_Data_Structure,
                                  AI_Process_Improve_Cache_Locality,
                                  AI_Process_Remove_Redundant_Materials,
                                  AI_Process_Fix_Infacing_Normals,
                                  AI_Process_Sort_By_PType,
                                  AI_Process_Find_Degenerates,
                                  AI_Process_Find_Invalid_Data,
                                  AI_Process_Gen_UV_Coords,
                                  AI_Process_Transform_UV_Coords,
                                  AI_Process_Find_Instances,
                                  AI_Process_Optimize_Meshes,
                                  AI_Process_Optimize_Graph,
                                  AI_Process_Flip_UVs,
                                  AI_Process_Flip_Winding_Order,
                                  AI_Process_Split_By_Bone_Count,
                                  AI_Process_Debone);
   pragma Convention (C, AI_Post_Process_Steps);

private
    for AI_Post_Process_Steps use (AI_Process_Calc_Tangent_Space        => 16#1#,
                                  AI_Process_Join_Identical_Vertices    => 16#2#,
                                  AI_Process_Make_Left_Handed           => 16#4#,
                                  AI_Process_Triangulate                => 16#8#,
                                  AI_Process_Remove_Component           => 16#10#,
                                  AI_Process_Gen_Normals                => 16#20#,
                                  AI_Process_Gen_Smooth_Normals         => 16#40#,
                                  AI_Process_Split_Large_Meshes         => 16#80#,
                                  AI_Process_Pre_Transform_Vertices     => 16#100#,
                                  AI_Process_Limit_Bone_Weights         => 16#200#,
                                  AI_Process_Validate_Data_Structure    => 16#400#,
                                  AI_Process_Improve_Cache_Locality     => 16#800#,
                                  AI_Process_Remove_Redundant_Materials => 16#1000#,
                                  AI_Process_Fix_Infacing_Normals       => 16#2000#,
                                  AI_Process_Sort_By_PType              => 16#8000#,
                                  AI_Process_Find_Degenerates           => 16#10000#,
                                  AI_Process_Find_Invalid_Data          => 16#20000#,
                                  AI_Process_Gen_UV_Coords              => 16#40000#,
                                  AI_Process_Transform_UV_Coords        => 16#80000#,
                                  AI_Process_Find_Instances             => 16#100000#,
                                  AI_Process_Optimize_Meshes            => 16#200000#,
                                  AI_Process_Optimize_Graph             => 16#400000#,
                                  AI_Process_Flip_UVs                   => 16#800000#,
                                  AI_Process_Flip_Winding_Order         => 16#1000000#,
                                  AI_Process_Split_By_Bone_Count        => 16#2000000#,
                                  AI_Process_Debone                     => 16#4000000#);

end Post_Process;
