
package Composite is

   type Composite_Operator is (Undefined_Composite_Op,
                               No_Composite_Op,
                               ModulusAdd_Composite_Op,
                               Atop_Composite_Op,
                               Blend_Composite_Op,
                               Bumpmap_Composite_Op,
                               ChangeMask_Composite_Op,
                               Clear_Composite_Op,
                               ColorBurn_Composite_Op,
                               ColorDodge_Composite_Op,
                               Colorize_Composite_Op,
                               CopyBlack_Composite_Op,
                               CopyBlue_Composite_Op,
                               Copy_Composite_Op,
                               CopyCyan_Composite_Op,
                               CopyGreen_Composite_Op,
                               CopyMagenta_Composite_Op,
                               CopyOpacity_Composite_Op,
                               CopyRed_Composite_Op,
                               CopyYellow_Composite_Op,
                               Darken_Composite_Op,
                               DstAtop_Composite_Op,
                               Dst_Composite_Op,
                               DstIn_Composite_Op,
                               DstOut_Composite_Op,
                               DstOver_Composite_Op,
                               Difference_Composite_Op,
                               Displace_Composite_Op,
                               Dissolve_Composite_Op,
                               Exclusion_Composite_Op,
                               HardLight_Composite_Op,
                               Hue_Composite_Op,
                               In_Composite_Op,
                               Lighten_Composite_Op,
                               LinearLight_Composite_Op,
                               Luminize_Composite_Op,
                               MinusDst_Composite_Op,
                               Modulate_Composite_Op,
                               Multiply_Composite_Op,
                               Out_Composite_Op,
                               Over_Composite_Op,
                               Overlay_Composite_Op,
                               Plus_Composite_Op,
                               Replace_Composite_Op,
                               Saturate_Composite_Op,
                               Screen_Composite_Op,
                               SoftLight_Composite_Op,
                               SrcAtop_Composite_Op,
                               Src_Composite_Op,
                               SrcIn_Composite_Op,
                               SrcOut_Composite_Op,
                               SrcOver_Composite_Op,
                               ModulusSubtract_Composite_Op,
                               Threshold_Composite_Op,
                               Xor_Composite_Op,
                               --  These are new operators,
                               --  added after the above was last sorted.
                               --  The list should be re-sorted only when
                               --  a new library version is created.
                               DivideDst_Composite_Op,
                               Distort_Composite_Op,
                               Blur_Composite_Op,
                               PegtopLight_Composite_Op,
                               VividLight_Composite_Op,
                               PinLight_Composite_Op,
                               LinearDodge_Composite_Op,
                               LinearBurn_Composite_Op,
                               Mathematics_Composite_Op,
                               DivideSrc_Composite_Op,
                               MinusSrc_Composite_Op,
                               DarkenIntensity_Composite_Op,
                               LightenIntensity_Composite_Op);
   pragma Convention (C, Composite_Operator);


end Composite;
